### ISSUE TITLE
Make time entry optional in expenses

### ISSUE THREAD

**Issue by EduNetEurope** [kevinpapst/kimai-plugins#103]
Our expenses have a day (date of the invoice). However, the time entry does not really apply or make sense.

Please make the time entry optional in expenses.

**Comment by kevinpapst** [comment]
Absolutely agree. Removed field with the latest release 2.8.0

**Comment by pbksol** [comment]
Ehh… No, keep the field just make it optional.
Let's name one example. Expenses are used to log driving distances for a customer. With the time this entry is 100% relatable to an arrival and quitting time. Without it's just something that happened on the day. Without any possible relation.
Same for let's say parking tickets and such.
Only two examples.

**Comment by kevinpapst** [comment]
Example 1: which time do you use, start or end? should be enough to say "arrival" or "return". Expenses are for calculating costs, not a drivers logbook.

Example 2: the missing feature is "attach receipt", not the time.

But I agree, if you need it, there are likely others as well. Thanks for the feedback.

**Comment by kevinpapst** [comment]
field will be shown by default, but can be hidden through a system setting.
time points to 12:00 by default
