### ISSUE TITLE
Expenses: Bug? Setting "adds expenses to consumed budgets" is active, but remaining budgets not reduced by billable expenses

### ISSUE THREAD

**Issue by EduNetEurope** [kevinpapst/kimai-plugins#104]
The setting "adds expenses to consumed budgets" is active:
![image](https://github.com/kevinpapst/kimai-plugins/assets/148647197/b66cff15-c8aa-42ee-bcb4-32af608cfb42)

However, expenses do not reduce the remaining budget:
![image](https://github.com/kevinpapst/kimai-plugins/assets/148647197/7fcb13fb-37bc-435e-ac4f-c7be79e04e3d)

Is this not what this setting should do?

**Comment by kevinpapst** [comment]
<img width="897" alt="Bildschirmfoto 2023-10-23 um 23 50 09" src="https://github.com/kevinpapst/kimai-plugins/assets/533162/6f3dc3c2-e99e-4623-91cd-1add6f5976cc">

**Comment by EduNetEurope** [comment]
Could it be that it only covers expenses that are created after the setting has been activated?
