### ISSUE TITLE
Expenses / upload files

### ISSUE THREAD

**Issue by christian-lo** [kevinpapst/kimai-plugins#113]
Hi,
uploading files (PDF) for expenses (e.g. bills) would increase functionality and productivity by a lot. 

In a perfect solution these files will be added as additional pages (or attached PDF) for each invoice and allow expenses handling in a single place.

Thanks a lot,
cheers,
Christian

**Comment by kevinpapst** [comment]
Please vote for #26 

Closing as duplicate
