### ISSUE TITLE
DeductionTime / costs are not substracted

### ISSUE THREAD

**Issue by christian-lo** [kevinpapst/kimai-plugins#114]
Hi, 
when using the DeductionTimeBundle the time in timesheet are correctly summed up but costs (defined in the project) are added instead of substracted for times marked as substraction. 
Please see the screenshot attached. 
<img width="1526" alt="Bildschirmfoto 2023-12-21 um 12 30 32" src="https://github.com/kevinpapst/kimai-plugins/assets/81588467/aa9f7b65-1d28-4cae-ad1b-92556e282088">

**Comment by kevinpapst** [comment]
https://github.com/Keleo/DeductionTimeBundle/issues

This feature does not exist and will not be added.
Simply make the deduction activity "not billable".

**Comment by christian-lo** [comment]
Thanks for the feedback! 
Even though I set the activity to "not billable" costs will be shown within exports or in views where a filter is applied.

<img width="589" alt="Bildschirmfoto 2023-12-21 um 17 23 17" src="https://github.com/kevinpapst/kimai-plugins/assets/81588467/b8032fe4-a5be-492c-9409-bca4ea58ecc4">
<img width="697" alt="Bildschirmfoto 2023-12-21 um 17 22 08" src="https://github.com/kevinpapst/kimai-plugins/assets/81588467/611330fd-59e9-4eee-9288-0ba4592a99de">

**Comment by kevinpapst** [comment]
Yeah, the price should be 0 then?

**Comment by christian-lo** [comment]
The price is set in the project and calculated automatically. I'm also not able to manually adjust as it's not saving any changes. 
Looks like a bug to me.

**Comment by kevinpapst** [comment]
You have to set the price on the deduction activity

**Comment by christian-lo** [comment]
uh… that should be added to the documentation that 1) you have to adjust "not billable" and 2) set costs to 0€. 
Thanks for the support.

**Comment by kevinpapst** [comment]
It always depends on the use-case that you want to use this plugin for...
