### ISSUE TITLE
Deduction Time / Costs and Invoice

### ISSUE THREAD

**Issue by christian-lo** [kevinpapst/kimai-plugins#118]
Hi, I already raised Issue #114 but you closed it and I still think it's a serious bug! 

I've set up a project with 100€ hourly costs. And I set up an activity as deduction time and not billable.
Then I track 6hrs working time on the project and 30min. deduction time. 

I would expect that kimai will sum up time and costs for this project as 5:30hrs billable time which result in 550€ billable costs.
In fact kimai either sums up the 6hrs with +600€ and deducts 30mins. pause with +50€ which result in a total of 5:30hrs working time but 650€ billable costs. Or when you manually set the costs for the specific deduction times to 0€ kimai sums up the 6hrs with +600€ and deducts 30mins. pause with 0€ which result in a total of 5:30hrs working time but 600€ billable costs. Both approaches are wrong! And not just the filtered sums are wrong but also when you create an invoice based on these tracked times! In the worst case you're billing your customers not just additional for your pause but doubled! 

<img width="575" alt="Bildschirmfoto 2024-01-05 um 11 30 51" src="https://github.com/kevinpapst/kimai-plugins/assets/81588467/84fa8569-8b23-419c-8a14-5156b64ca28b">
<img width="1517" alt="Bildschirmfoto 2024-01-05 um 11 31 49" src="https://github.com/kevinpapst/kimai-plugins/assets/81588467/cc770cc0-6974-4f44-8efb-7bafa894fbbd">

Solution could be that…
1) Deduction times are just also use negative values for costs or
2) Deduction times are always 0€ and for sums as well as invoices not the pre-calculated times / cots are summed up but the sum of real times + deduction times are multiplied by the cots of the project

**Comment by kevinpapst** [comment]
1. You are trying to achieve something that was not planned.
2. I will close this again, as this repository is only for paid plugins.

The entire bundle was built for a certain use-case and paid by a customer, who was willing to share it with the community.

The deduction time bundle is free to use, without any warranty. 
https://github.com/Keleo/DeductionTimeBundle  

Want more features? Sure. You can build them yourself or you post a new issue:
https://github.com/Keleo/DeductionTimeBundle/issues
