### ISSUE TITLE
Expenses - feature request - modify permission

### ISSUE THREAD

**Issue by gabrielebrognoli** [kevinpapst/kimai-plugins#126]
Please, add the ability to change the expense cost as an attribute of the individual category and not the user's profile.
For example, you need to change the amount spent on train ticket, but not the cost per kilometer when using the car.

Thanks

**Comment by gabrielebrognoli** [comment]
It's true, but if I configure a fixed cost and anyone can change it, the accountants have to verify the correctness of the amounts every time

**Comment by kevinpapst** [comment]
How can everyone change it? Only Admins can see the price field. Normal user only see the amount field.

> accountants have to verify the correctness of the amounts

Isn't that the exact job description of an accountant?

**Comment by gabrielebrognoli** [comment]
> How can everyone change it? Only Admins can see the price field. Normal user only see the amount field.

Ah, ok! I now understand your previous sentence...

> You either configure a price and the user enters an amount (kilometer) or **you configure no price (AKA the price 1)** and the user enters the costs (train ticket).

 
> > accountants have to verify the correctness of the amounts
> 
> Isn't that the exact job description of an accountant?

yes, of course, but information technology serves to simplify the lives of accountants too ;-)

Anyway, thanks for the explanations and patience :)

**Comment by kevinpapst** [comment]
> yes, of course, but information technology serves to simplify the lives of accountants too ;-)

Obviously! I just forgot the 😁
