### ISSUE TITLE
Working Contract: Feature Request - keeping overtime when changing worktime, pro rata vacation and transfer of not-taken vacationtime

### ISSUE THREAD

**Issue by intelliIT** [kevinpapst/kimai-plugins#128]
We have quite a few users changing working contract in the upcoming period, most of the starting to work fulltime.
I did not find a solution yet to let them keep their overtime hours properly when changing into a new working contract.
Maybe just add a custom field on the profile where i can add a per-user amount of overtime they start their new contract with.

Also i have a user started last year in september, who has the full 30 days vacation time available, where he should have 30/12*3 days available. Also he didnt take all of his days last year, so he should still have them available for the new year 2024, which he does not.

**Comment by kevinpapst** [comment]
Kimai is used in the entire world and does not (yet) care about national regulations.
The rule 30/12*3 is maybe legit is your country, not in others.

> i have a user started last year in september, who has the full 30 days vacation time available, where he should have 30/12*3 days available. 

Kimai calculates everything per calendar year.
For the first year, you have to calculate and enter the number manually.
After the first year, you can change the configuration and enter 30 days.

> Also he didnt take all of his days last year, so he should still have them available for the new year 2024, which he does not.

You have to carry overtime and vacation days over into the next year manually.
Kimai will not do that automatically (yet) for you. Ever working contract is different and both overtime and vacation days might be deleted at the end of the year. Yes, that is a normal rule in certain countries.

There are the two boxes for "manual bookings" which can be used to change the hour & vacation balance:
<img width="616" alt="Bildschirmfoto 2024-01-30 um 11 14 31" src="https://github.com/kevinpapst/kimai-plugins/assets/533162/d89b7a2a-5ea3-4f71-8bf7-28dbc2b45c5a">

> We have quite a few users changing working contract in the upcoming period, most of the starting to work fulltime.
I did not find a solution yet to let them keep their overtime hours properly when changing into a new working contract.

After "closing" a month, the numbers are written to a different database table and locked. You have to close all month in the past!
After that, you can change the working contract and Kimai will not recalculate the past.
So: working contracts can change, but ONLY at the start of a month.

> Maybe just add a custom field on the profile where i can add a per-user amount of overtime they start their new contract with.

See above. Create manual bookings for vacation days and hours.

Next time, please ask multiple questions in the discussion area: https://github.com/kevinpapst/kimai-plugins/discussions
