### ISSUE TITLE
Plugin - Custom Fields - Restrict Visibility Not Working

### ISSUE THREAD

**Issue by corrigenda-admin** [kevinpapst/kimai-plugins#138]
Hi,

We have the "Custom Fields" plugin and its not working when we try to limit the visibility.

When we put in a Permission like "budget_team_activity" it works fine. But when we put in a full "Role" like "ROLE_ADMIN" it doesnt show when a member of that group goes to the screen.

I have tested it on your demo platform and get the same output incase it was just platform specific to us.

I have attached a screenshot of the name I have put in the restriction part but doesnt show at all on the screen.

![image](https://github.com/kevinpapst/kimai-plugins/assets/119504812/e1aab451-7cc7-46fa-a07b-20c2b38361a9)

**Comment by corrigenda-admin** [comment]
To add further to this. It seems to be when we allocate it to a custom created "Role", the system defined ones seem to be ok?

**Comment by corrigenda-admin** [comment]
Thanks for the reply, 

Sorry to explain further on my second comment.

If i put in the Restrict Visibility to "ROLE_ADMIN" it seems to work ok.

But, when i create a custom role "SOLENT" and allocate the user to that, and change the Restrict to "SOLENT" it doesnt show. So seems to be when I create roles? They are definitely following the same name.

I have attached some screenshots to try to help explain.
![Limit_Role_Admin](https://github.com/kevinpapst/kimai-plugins/assets/119504812/97012562-7803-4911-b0c2-1476086fa2f7)
![Limit_Role_Admin_Working](https://github.com/kevinpapst/kimai-plugins/assets/119504812/10186254-644d-4559-b362-436135457849)
![Permission _ SOLENT](https://github.com/kevinpapst/kimai-plugins/assets/119504812/08718531-9615-453e-b983-5f05af4161e4)
![Role Group - Test - Not working](https://github.com/kevinpapst/kimai-plugins/assets/119504812/0c0b142e-c74d-40ed-89a8-1f404ac60602)
![Role Group _ Admin _ Working](https://github.com/kevinpapst/kimai-plugins/assets/119504812/016b9333-8dab-467c-bfdc-9fa0389f690f)
![ROLES](https://github.com/kevinpapst/kimai-plugins/assets/119504812/dfcde6dc-b653-4938-b507-7af16a73b176)
![SOLENT _ Not showing](https://github.com/kevinpapst/kimai-plugins/assets/119504812/3f17777a-82f6-4585-8f44-fa4769f7bc2d)

**Comment by kevinpapst** [comment]
Please try `ROLE_SOLENT` as name

**Comment by kevinpapst** [comment]
Okay, found it. The important part of the documentation is here:
https://www.kimai.org/documentation/permissions.html#creating-roles

Quote:
> Custom role names must start with ROLE_ and need to be written in uppercase letters, so instead of using Manager you have to create ROLE_MANAGER. This is required if you want to test for role permissions programmatically.

I added it to the new chapter about "visibility of custom fields" here:
https://www.kimai.org/documentation/plugin-custom-fields.html#visibility

**Comment by corrigenda-admin** [comment]
Fantastic, thank you so much!! Really appreciate the support. Love the work you do as well. Such a great program.

**Comment by kevinpapst** [comment]
Sorry that have to change your role name now 😊 

But discussions like this one are important for me, so I can identify pieces in the documentation that are missing!
