### ISSUE TITLE
improve contract plugin working times view for team leads

### ISSUE THREAD

**Issue by derStephan** [kevinpapst/kimai-plugins#140]
### Describe the problem

In the working times view there is a user selection for administrators but not for team leads.

### Describe the solution you'd like

It would be great to have the same user selection as for monthly reports if I am a team lead.

**Comment by kevinpapst** [comment]
That is a permission question:
https://www.kimai.org/documentation/contract.html#permissions

You can always add more people / roles to the list of allowed people.

**Comment by derStephan** [comment]
I see, it is working now. Thanks for the information. However, now team leads can change planned working hours or vacancy days for the team including their own settings. 

May I suggest to devide that in 2 different rights to prevent errors or fraud? One for simply viewing the working times and the other for changing user profiles.

**Comment by kevinpapst** [comment]
Oh yes, I missed that one. Thanks for sharing 👍

**Comment by derStephan** [comment]
Do you know, when this will be fixed? I am running the latest 1.10.0 but the issue remains.

**Comment by kevinpapst** [comment]
Upgrade to the latest Kimai version and then fetch the latest plugin version at https://license.kimai.org/

The combination of both should do the trick.

**Comment by derStephan** [comment]
I just upgraded the plugin to version 1.11.0 and run it in Kimai 2.17.0 and Team leads are still able to change their own expected number of hours, the link to /profile/<username>/contract is still working.

I did not find any permission to prevent it.

**Comment by derStephan** [comment]
Ok, sorry. Must have missed it. Found the new permission `contract_other_profile` in `user profile (other)`. It is working like a charm now. Thanks.
