### ISSUE TITLE
Feature addition: Kiosk plugin minimum duration

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [kevinpapst/kimai-plugins#144]
Hi,
I have bought the kiosk plugin for a customer and I had to add a feature that adds a setting for a "minimum duration" of a timesheet entry. E.g. if someone scans their code to check-in and scans it again to check-out before "min duration" is elapsed the time sheet record will not get added.
I think this could be use full for everybody so I would like to share the changes I did to the kiosk plugin with you... what would be the best way to do so, if you are interested?

cheers

**Comment by kevinpapst** [comment]
Send your patched version to support@kimai.org - I will have a look

**Comment by tofuSCHNITZEL** [comment]
done.
cheers
