### ISSUE TITLE
Include audit trail in timesheets

### ISSUE THREAD

**Issue by Sim0nW0lf** [kevinpapst/kimai-plugins#48]
Recently I had to track down where a timesheet entry was coming from. I knew the audit trail plugin had this information somewhere but I couldn't find the corresponding audit trail entry.

In the end I could only find it by searching in the database for the timesheet id and look up the time of creation with that info in the audit trail plugin which I could filter then to find it in the audit trail web interface.

A simple connection somehow should be established to make it usable I think, also maybe number of changes or something showen in the timesheet.

Thank you very much for your development, it has been a really good tool so far!

**Comment by kevinpapst** [comment]
This information exists.

But you have to look it up through the "Administration > Timesheets" screen:
<img width="975" alt="Bildschirm­foto 2022-12-31 um 20 30 08" src="https://user-images.githubusercontent.com/533162/210153986-fa8c548b-6902-40b8-a2f6-0d37bc33b9f2.png">

**Comment by Sim0nW0lf** [comment]
Aaaah thank you very much, then this issue can be closed 😋

**Comment by kevinpapst** [comment]
Happy to help, next time ... you can ask before 😁
