### ISSUE TITLE
Aufgabenplanung Team-Aufgaben

### ISSUE THREAD

**Issue by NetBLOKS** [kevinpapst/kimai-plugins#54]
Aufgaben für Teams -> Jedes Mitglied soll Erfassung starten können und die Erfassung wird dem startenden User zugeordnet, bleibt aber für das Team sichtbar (im Grunde teilt sich das Team die Aufgabe)

**Comment by kevinpapst** [comment]
You can already achieve that users can start "pending" tasks. 

Please read the documentation, you have to toggle the permissions for that.

**Comment by NetBLOKS** [comment]
Yes, that works!
The Permission "start all" was missing.
Now I can also start non-pending Team-tasks.
I´ll check if that works for us as expected.
Thanks!
