### ISSUE TITLE
500 after installing custom fields 

### ISSUE THREAD

**Issue by navarts-design** [kevinpapst/kimai-plugins#58]
Hey there,
after installing the custom fields plugin i got the "something went wrong" page in my browser. 

after installation, i flushed the cache and reset file permissions.

the following error message i get in the prod.log file.

request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of KimaiPlugin\MetaFieldsBundle\EventSubscriber\AbstractCustomFieldSubscriber::getRulesForEntityType() must be of the type array, null returned" at /volume2/web/timetracking/kimai2/var/plugins/MetaFieldsBundle/EventSubscriber/AbstractCustomFieldSubscriber.php line 73 {"exception":"[object] (TypeError(code: 0): Return value of KimaiPlugin\\MetaFieldsBundle\\EventSubscriber\\AbstractCustomFieldSubscriber::getRulesForEntityType() must be of the type array, null returned at /volume2/web/timetracking/kimai2/var/plugins/MetaFieldsBundle/EventSubscriber/AbstractCustomFieldSubscriber.php:73)"} []

Kimai version: 1.22.1
PHP Version 7.4.3
Server Nginx (virtual server on Synology Nas)

Thanks for help

**Comment by kevinpapst** [comment]
Which plugin version are you using?

**Comment by kevinpapst** [comment]
Both errors do not make any sense. 
The "could not find driver" is an environment problem with PHP and has nothing to do with the plugin version.
And the first error may not happen, as Doctrine is supposed to always return an array and not null.

Synology has - unfortunately - not the best PHP environment...

Can you upgrade your Kimai, which is pretty old and the used libraries might have some incompatibilities with the Synology PHP. The plugin works find in hundreds of installations and we should rule out that this might be some bug in a dependency that was already fixed.

**Comment by navarts-design** [comment]
Hmm ok, then i will try to upgrade to version 1.30.5 can i still use this installation with PHP 7.4 or do i have to change PHP version for this also?

**Comment by navarts-design** [comment]
hey there! Sorry im a noop!!!! for installing the database table i forgot to prefix the install command with my php version (because i'm on synology). 

SORRY!!

so with "php74 bin/console kimai:bundle:metafields:install" 

the instalation works!

**Comment by kevinpapst** [comment]
Ah right, thats why the "driver not found" appeared 😁 

Thanks for your feedback!
