### ISSUE TITLE
Expenses: Invoice without timesheets

### ISSUE THREAD

**Issue by LiaraAlis** [kevinpapst/kimai-plugins#64]
It would be nice if it were possible to invoice expenses without having to record times for them. For example, a cancellation invoice could be created or only licenses that do not entail any work could be offered.

**Comment by kevinpapst** [comment]
That works. The invoice module internally doesn't even know Timesheets.
I do regularly create invoices purely based on Expenses.
Why do you think that does not work?

**Comment by LiaraAlis** [comment]
It doesn't work if the amount of the expenses are negative. The filter in the invoice module doesn't show any results until positive values do not occur somewhere (timesheets or expenses). I thought that it is needed to log any timesheet, but in fact the negative amount is the real problem.

**Comment by kevinpapst** [comment]
> in fact the negative amount is the real problem.

The negative amount is the **reason** why you cannot create an "invoice".

I am not a bookkeeper and do not know how to handle such cases. 
And Kimai isn't a full-fledged bookkeeping software.

You can remove that line, play around and share your experience:
https://github.com/kimai/kimai/blob/main/src/Invoice/ServiceInvoice.php#L535

**Comment by LiaraAlis** [comment]
Thank you. I will try it in the next days.
I understand that Kimai isn't a full-fledged bookkeeping software. But in my eyes it doesn't make sense if you can create an invoice but having no possibility to correct them. If you want to do this you need to another software for this. And if you use another software, you don't need kimai for that.

**Comment by kevinpapst** [comment]
thanks for your opinion 🤷

I myself - in 20 years of freelancing - had not once the need to correct an invoice. Yes, I created wrong invoices, then I deleted them and re-created them again. And I know customers who create dozens of invoices every month with Kimai and never asked for such a feature. 

Let be constructive and gather information to improve the current situation. 
E.g. how to handle taxes for negative amounts. What should happen there?

**Comment by LiaraAlis** [comment]
It is no problem to delete an invoice and create a new one as long as it has not been sent out to the customer.
Based on the legal situation in Germany, however, an invoice that has been issued may no longer be corrected. It always requires a correction or cancellation invoice. I don't know if there are other regulations in other countries.

From my point of view, if I want to cancel a previous issued invoice or parts of them, the tax should also be cancelled.
If you then subtract both invoices from each other, you should come out with 0 accordingly.

Of course, at the moment I can not say what problems this change may cause. So let me try it first and share my experience.

**Comment by LiaraAlis** [comment]
I finally managed to give the whole thing a try. Basically, the invoice creation seems to work even with negative values, if you comment out the above mentioned place.

![image](https://user-images.githubusercontent.com/297882/228112811-c6101cc3-8deb-4221-90c3-934f9c3cd683.png)
![image](https://user-images.githubusercontent.com/297882/228112840-fa668067-5e3b-44b2-90e3-8b29bf5e2de9.png)

But the representation of the currency may not be ideal yet.

**Comment by kevinpapst** [comment]
Yep, the major update already ships it: https://github.com/kimai/kimai/releases/tag/2.0.11

Thanks for testing 👍
