### ISSUE TITLE
Feature Request - Kiosk Plugin - Device Front Camera

### ISSUE THREAD

**Issue by navarts-design** [kevinpapst/kimai-plugins#65]
Hey there,
it would be great if you could add a select option to use Device Front Camera as barcode scanner. In the current version, I can select "Barcode via Device Camera".

In our office, we use a tablet that is fixed at the wall, and so we can't use back camera and have to switch to front camera. So i decided to extend your "Quagga.init" function (in KisokBundle/Resources/views/webcam.html.twig on line:35) with:

...
constraints: {
width: {min: 640},
height: {min: 480},
facingMode: "user",
aspectRatio: {min: 1, max: 2}
}
...

After that, all mobile devices are using Front Camera. But at the moment it is just hard coded to your files.

Can you maby tell me how to add this code update safe?
Or if you like my idea of setting this as general select option "Barcode via Device Front Camera", just add this as option in your installation. It would be great.

Thanks for all and have a good day

**Comment by kevinpapst** [comment]
I added a camera switcher for the next version 2.1.0 (needs Kimai 2.x).
<img width="808" alt="Bildschirm­foto 2023-04-19 um 17 42 42" src="https://user-images.githubusercontent.com/533162/233128832-fcce8281-e767-43fb-b924-0591a022d0ff.png">
This dropdown can be deactivated, Inputs are derived from the device browser (which needs the device permission).

**Comment by navarts-design** [comment]
Hey There, 
perfect! I'm looking forward to testing in the new release! Thanks

**Comment by kevinpapst** [comment]
Can be tested via the v2 demo. Go to https://www.kimai.org/en/demo.html and then choose this demo:

<img width="629" alt="Bildschirm­foto 2023-04-20 um 12 43 45" src="https://user-images.githubusercontent.com/533162/233343117-3ef55fb5-1d41-4d2c-9b1c-403a53d8e70d.png">
