### ISSUE TITLE
Update plugins on gumroad

### ISSUE THREAD

**Issue by TheZoker** [kevinpapst/kimai-plugins#68]
I saw that there is a new version e.g. for the custom fields plugins:
![image](https://user-images.githubusercontent.com/1368405/236065069-f1be0df8-b2b7-40fd-8f64-3f8b4c069db3.png)

But on gumroad, there is only version 
![image](https://user-images.githubusercontent.com/1368405/236065156-67ad87d9-37b6-41fa-b986-793b42bcfa04.png)

Can you please upload the latest version on gumroad? Thanks!

**Comment by kevinpapst** [comment]
I am overloaded with work right now, but News will follow on this topic.

**Comment by TheZoker** [comment]
Just out of curiosity:
What is the best place to follow news about this project? Is there something like a discourse/discord/slack etc.?
Or just the news section on the website?

**Comment by kevinpapst** [comment]
News and: Twitter or Mastodon.
