### ISSUE TITLE
Column not found: 1054 Unknown column 'option' in 'where clause'

### ISSUE THREAD

**Issue by hyssop** [kevinpapst/kimai-plugins#73]
Trying to migrate from 1.30.11 to 2.0.22 and getting this error.

I assume it's a column in v1 called 'option' that doesn't exist in v2, but I'm unable to find it.

CRITICAL  [console] Error thrown while running command "kimai:import:v1 --global --language=en --country=US --currency=USD --prefix=kimai2_ 'mysql://user:password@localhost:3306/database?charset=utf8' new_password". Message: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'option' in 'where clause'" ["exception" => Doctrine\DBAL\Exception\InvalidFieldNameException^ { …},"command" => "kimai:import:v1 --global --language=en --country=US --currency=USD --prefix=kimai2_ 'mysql://user:password@localhost:3306/database?charset=utf8' new_password","message" => "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'option' in 'where clause'"]

In ExceptionConverter.php line 67:
An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'option' in 'where clause'

In Exception.php line 28:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'option' in 'where clause'

In Statement.php line 121:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'option' in 'where clause'

kimai:import:v1 [--country [COUNTRY]] [--currency [CURRENCY]] [--prefix PREFIX] [--timezone [TIMEZONE]] [--language [LANGUAGE]] [--global] [--fix-utf8] [--fix-email FIX-EMAIL] [--fix-timesheet] [--skip-error-rates] [--merge-customer] [--merge-project] [--merge-user] [--merge-team] [--create-team] [--alias-as-account-number] [--meta-comment META-COMMENT] [--meta-location META-LOCATION] [--meta-tracking-number META-TRACKING-NUMBER] [--skip-teams] [--skip-team-customers] [--skip-team-projects] [--skip-team-activities] [--check-already-imported] [--] <connection> <password>

**Comment by kevinpapst** [comment]
you know that the command is for Kimai 1, which is 15 years old: https://www.kimai.org/documentation/migration-v1.html ?

**Comment by kevinpapst** [comment]
Just updates as always, don't overcomplicate things: https://www.kimai.org/documentation/updates.html

**Comment by hyssop** [comment]
Thanks... I misread the page migrate page, thinking there were 2 migrate paths for newer and old v1 installs. Oops...

Initially I was trying to use the Importer to import from 1.30.11 to 2.0.22, but wasn't having good results, and even the sample from 2.0.22 Importer sample files wouldn't upload back into it (mime type error, probably due to Windows screwing it up).  

I'll clone the v1 install and update it that way... much easier.
