### ISSUE TITLE
Possibility to enter a break during the time tracking as well

### ISSUE THREAD

**Issue by jensbaeumler** [kevinpapst/kimai-plugins#76]
We often have training sessions with fixed times: 
Start 9 a.m., end at 5 p.m.
Coffee break at 10:30 and 14:45
Lunch break at 12:15

It would be nice if we could change the duration independently of the start and end or add a break.

Start 9 am
End 5 pm
Break 2 hours

Or 
Start 9 o'clock
End 5 pm
Duration 6 hours

**Comment by kevinpapst** [comment]
There are many issues that talk about such an issue:
https://github.com/kimai/kimai/issues?q=is%3Aissue+is%3Aopen+break

Please vote and discuss there.
This repository here is for my paid plugins, the other one for the core software.
