### ISSUE TITLE
Import META-Fields via CSV-Import

### ISSUE THREAD

**Issue by wobouser** [kevinpapst/kimai-plugins#81]
Hi,

Kimai: 2.0.26
PHP-Version: 8.1.20
OS: Debian 10 / OnPrem
Plugins:
  Custom fields 2.0.7
  CSV Importer 2.2.1
Tested Browser: Chrome / FireFox / Edge

we use csv importer via webui the first time.

the old school way

`bin/console kimai:import:customer customer.csv --reader=csv-semicolon`

seems to no longer exist ?

when i pull in the csv via the importer everything looks good:

![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/2aec993e-3146-4a33-8f6c-00b419e41fef)

![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/7d7bc4c0-cc61-48e6-8b96-d0eee95f4863)

in the customer itself is no data in the meta field

![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/8f7b5d57-7ccb-4f26-8e78-bde7175df501)

thats the custom field

![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/b7253a61-5fc4-4dc1-9c43-8b93543d0971)

also nothing to see in the sql database

![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/5aba93a9-cd9f-49bd-b327-4de28bcdfec9)

![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/b79c5094-7b84-4dae-a39b-bdbf48f645f9)

**Comment by wobouser** [comment]
PS: 
we have updated from 1.30.11 -> 2.0.25 -> 2.0.26 (with freshly installed plugins)

**Comment by kevinpapst** [comment]
The importer does not support meta fields (yet):
https://www.kimai.org/documentation/plugin-import.html#timesheets

**Comment by wobouser** [comment]
ok, but under -> https://www.kimai.org/documentation/plugin-import.html#customer

> Supported attributes (field names are case-insensitive):
Meta fields | meta.xxx

and 

> A multi column-example:
Name,Company,Number,Comment,Phone,Timezone,Meta.XYZ
Acme,Acme university Ltd.,12367800,A longer comment to talk about the project,0011234567890,Europe/Berlin,hello foo 123

METAs are listed.

Is there another way to import customers with metafields (like the console way) ?

**Comment by wobouser** [comment]
thanks a lot
