### ISSUE TITLE
Access to META-Fields in Invoices / pdf.twig

### ISSUE THREAD

**Issue by wobouser** [kevinpapst/kimai-plugins#82]
Hi,

Kimai: 2.0.26
PHP-Version: 8.1.20
OS: Debian 10 / OnPrem
Plugins:
Invoicing enhanced 2.0.3

my old pdf.twig for invoices (from Kimai 1.30.11) wont work anymore with META-fields in Kimai 2.0.26

old way:
Definiton
`{% set metaDummy = entry.getMetaFieldValue('dummy_field') %}`

Output:
`{% if metaDummy is not null %}
     {{ metaDummy }}
{% endif %}`

Error:
![image](https://github.com/kevinpapst/kimai-plugins/assets/84374962/5c2e8b9c-17ee-4958-adb7-3d8d2f0682eb)

from -> https://www.kimai.org/documentation/invoices.html#twig-templates

`{% if line['entry.meta.dummy_field'] is defined %}
    Foo: {{ line['entry.meta.dummy_field'] }}
{% endif %}`

the output is empty.

where is my mistake ?

**Comment by kevinpapst** [comment]
I need to see at least the entire loop over all invoice rows.
It looks okay to me at the first glance.

Please install the debug template: copy & paste from the docs at:
https://www.kimai.org/documentation/invoices.html#twig-templates
And check the output.

**Comment by wobouser** [comment]
has helped :-)
thank you.

ticket can be closed ^^
