### ISSUE TITLE
Bug: Expenses / special character

### ISSUE THREAD

**Issue by christian-lo** [kevinpapst/kimai-plugins#88]
If you use a special character within the description e.g. "&" it's "translated" into &amp; in the export (PDF).

thanks!

**Comment by kevinpapst** [comment]
???

Could you take two more seconds to clearly explain whx it is a problem that `&` is a `&`.
Which export are you talking about?

**Comment by christian-lo** [comment]
argh... sorry, the `&amp` got translated into & by github, sorry.

**Comment by kevinpapst** [comment]
Works for me. I need more details:
Which export: expenses directly or export screen?
Which PDF type?
Which Kimai and which plugin version?

**Comment by kevinpapst** [comment]
@christian-lo see my last response: it works here, so I need more input or I will close this issue

**Comment by kevinpapst** [comment]
No response, closing
