### ISSUE TITLE
Restore functionality from V1 -- allow creation of tasks without due date

### ISSUE THREAD

**Issue by pbksol** [kevinpapst/kimai-plugins#89]
Version 1.x of the Tasks Management Plugin allowed the creation of tasks without setting a due date. This was super useful to create tasks which are not time critical but need to be done sometimes. E.g. technician is on site and can work through such tasks.

With version 2 of the tasks plugin the due date is mandatory and it's no longer possible to create such "floating" tasks. This breaks some well established workflows and renders this plugin more or less useless for our use cases.

Fun part: the date field is not even marked as mandatory (no star).

Maybe we're doing something wrong but we could not find a way to create tasks without entering a date since switching to v2.

**Comment by kevinpapst** [comment]
Agree, actually that looks like a bug to me. 
I'll have to check what is happening there.

Thanks for the info 👍

**Comment by kevinpapst** [comment]
Will be fixed with the upcoming release 2.0.31 https://github.com/kimai/kimai/pull/4245
