### ISSUE TITLE
Critical Login Issue with Kimai v2 on PHP 8.1

### ISSUE THREAD

**Issue by atxcowboy** [kevinpapst/kimai-plugins#90]
PHP Version: 8.1 (recommended as per Kimai docs)
Web Servers: Tested on both Apache and Nginx
Document root: Configured to the public/ folder as required
**Problem Description:** When attempting to log in, the script exits, and the following errors are observed:

- With PHP-FPM: (104: Connection reset by peer) while reading response header from upstream
- With Apache+mod_lsapi: Error on sending request(POST /en_US/login_check HTTP/1.1); uri(/index.php) content-length(174): ReceiveAckHdr: nothing to read from backend (LVE ID 1167)
- When switching to PHP 7.4, the page loads but throws an error requiring PHP ">= 8.1.2".

**Steps Taken:**

- Adjusted the document root to public/, following the expected Kimai configuration.
- Tested with both Apache and Nginx to rule out server-specific issues.
- Attempted to use an Apache proxy but couldn't obtain a log entry.
- Allocated substantial resources to the PHP process (2048M RAM) to rule out resource limitations.
- Despite these efforts, the issue persists, and it seems to be related to the application itself, as the PHP process appears to exit unexpectedly.

**Comment by kevinpapst** [comment]
This repo is only for support of paid plugins.
Please post Kimai issues here: https://github.com/kimai/kimai/issues

I can tell you right away that Kimai works with 8.1 and this is an environment issue.
