### ISSUE TITLE
Allow expanding collapsed card by clicking the entire header

### ISSUE THREAD

**Issue by pbksol** [kevinpapst/kimai-plugins#92]
Can this be changed for the plugins, too?

Link to the fixed Kimai issue: (https://github.com/kimai/kimai/pull/4096)

This affects all plugins with collapsed card data

Thanks a million :-)

**Comment by christian-lo** [comment]
oh yes, please! for the expense plugin it does not work so far.

cheers, christian

**Comment by kevinpapst** [comment]
Thanks! 

> for the expense plugin it does not work so far

Fixed in Expenses - already released in Lemonsqueezy.

> This affects all plugins with collapsed card data

@pbksol I need help finding all occurences, do you know more ?

**Comment by pbksol** [comment]
@kevinpapst Expenses and Tasks are the two occurrences I know of

**Comment by kevinpapst** [comment]
Alright, then I am closing here. Both have been fixed and uploaded to Lemonsqueezy.
If you see more issue after updating them, please let me know!

**Comment by pbksol** [comment]
Works 👍 – Thank you :-)
