### ISSUE TITLE
Working hours, vacation, illness (controlling) not shown after install

### ISSUE THREAD

**Issue by PentaPaetzold** [kevinpapst/kimai-plugins#96]
Today i installed the Plugin "Working hours, vacation, illness (controlling)".
I did an update for Kimai from 2.0.30 to 2.0.32, extracted the zip and did the installation and cache refresh.
```
4971ffc1ed8f:/var/www/html# /opt/kimai/bin/console kimai:bundle:workcontract:install
Starting installation of plugin: WorkContractBundle ...
=======================================================
[notice] Migrating up to WorkContractBundle\Migrations\Version20230818221404
[notice] finished in 271.5ms, used 24M memory, 4 migrations executed, 12 sql queries
 [OK] Successfully migrated to version : WorkContractBundle\Migrations\Version20230818221404                            
 [OK] Congratulations! Plugin was successful installed: WorkContractBundle 

```
I don't see any error messages in logs.

In the Plugin- View i can see "Working Contract" in Version 1.0.1. But i do not see any settings in user, nor the Section "Employment contract" as the demo offers - everything looks as before.
What could be the reason and how to make it work? Maybe there is a problem with German language (missing translations)? We would be fine to see english text if no translation would be available.

**Comment by kevinpapst** [comment]
Nah, translations aren't the issue. It should be translated to German and english 100% and partially to many others as well.
What user account did you try?
System-Admins see the menu by default.
Users see the menu as soon as they have active Contract settings.

Check if your current user has the `contract_other_profile` permission through his roles.

**Comment by PentaPaetzold** [comment]
Jepp - even superadmin did not had that permission enabled. Setting it to yes worked. Don't now why it was not activated by default. Maybe add a hint in docs to check for that permission after install?

Otherwise: works! perfect, thanks!

**Comment by kevinpapst** [comment]
Super weird. The demo reinstalls twice a day with a fresh installation. Maybe there is some issue with updated systems. I'll investigate. Sorry for the hickup-installation 😊

**Comment by kevinpapst** [comment]
I updated the docs , closing here
