### ISSUE TITLE
Tasks API queries returning contents of last page for non existent pages

### ISSUE THREAD

**Issue by pbksol** [kevinpapst/kimai-plugins#97]
Old behaviour: /api/tasks returned an empty or 404 result if a page was requested that did not exists
New behaviour: If you request a page way out of range always the contents of the last existing page is returned

To simplify things, here's a sample request for demo.kimai:

[Real last page](https://paw.pt/h84kF4ee)
[Requesting page 300](https://paw.pt/h84iP8qw)

This is currently killing all Task API stuff :-(
We fixed it temporarily by comparing the returned data with the previous page so take your time :-)

**Comment by kevinpapst** [comment]
True. Expenses as well, unfortunately. 

I fixed https://github.com/kimai/kimai/issues/4279 in https://github.com/kimai/kimai/pull/4273/files but forgot to adapt the plugins that have an API.

Fix is on the way, I'll update here later.

**Comment by kevinpapst** [comment]
Uploaded new versions to Lemonsqueezy, can you please retry!?

**Comment by pbksol** [comment]
I checked with Tasks and Expenses and empty pages return a 404 as expected again.

Thanks for the quick fix. I know that obviously nobody else is using the API. Many kudos for maintaining it nonetheless. The API and the possibility to make it sync with other systems is one important reason why Kimai is used.

**Comment by kevinpapst** [comment]
Yeah, I am really not sure if the Task API is heavily used. 
But an API belongs to every plugin, at least if it is requested by one person. 

I think every software should be able to be queried from the outside world.
